==> Making package: python2-scandir 1.10.0-1 (Wed Mar 20 14:45:15 2019)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (1) python2-2.7.15-7

Total Installed Size:  71.56 MiB

:: Proceed with installation? [Y/n] checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing python2...
Optional dependencies for python2
    tk: for IDLE
    python2-setuptools
    python2-pip
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (5) python2-appdirs-1.4.3-2  python2-packaging-18.0-1  python2-pyparsing-2.3.1-1  python2-six-1.12.0-1  python2-setuptools-1:40.6.3-1

Total Installed Size:  2.89 MiB

:: Proceed with installation? [Y/n] checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing python2-appdirs...
installing python2-pyparsing...
installing python2-six...
installing python2-packaging...
installing python2-setuptools...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Retrieving sources...
  -> Found python2-scandir-1.10.0.tar.gz
==> Validating source files with sha512sums...
    python2-scandir-1.10.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting python2-scandir-1.10.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
  warnings.warn(msg)
running build
running build_py
running build_ext
==> Starting check()...
test_iter_returns_dir_entry (test_scandir.TestScandirDirEntry) ... ok
test_basic (test_scandir.TestScandirGeneric) ... ERROR
test_bytes (test_scandir.TestScandirGeneric) ... ERROR
test_dir_entry (test_scandir.TestScandirGeneric) ... ERROR
test_file_attributes (test_scandir.TestScandirGeneric) ... ERROR
test_path (test_scandir.TestScandirGeneric) ... ERROR
test_returns_iter (test_scandir.TestScandirGeneric) ... ERROR
test_stat (test_scandir.TestScandirGeneric) ... ERROR
test_symlink (test_scandir.TestScandirGeneric) ... ERROR
test_unicode (test_scandir.TestScandirGeneric) ... ERROR
test_walk_unicode_handling (test_scandir.TestScandirGeneric) ... ERROR
test_basic (test_scandir.TestScandirPython) ... ERROR
test_bytes (test_scandir.TestScandirPython) ... ERROR
test_dir_entry (test_scandir.TestScandirPython) ... ERROR
test_file_attributes (test_scandir.TestScandirPython) ... ERROR
test_path (test_scandir.TestScandirPython) ... ERROR
test_returns_iter (test_scandir.TestScandirPython) ... ERROR
test_stat (test_scandir.TestScandirPython) ... ERROR
test_symlink (test_scandir.TestScandirPython) ... ERROR
test_unicode (test_scandir.TestScandirPython) ... ERROR
test_walk_unicode_handling (test_scandir.TestScandirPython) ... ERROR
test_traversal (test_walk.TestWalk) ... ok
test_symlink_to_directory (test_walk.TestWalkSymlink) ... ok
test_symlink_to_file (test_walk.TestWalkSymlink) ... ok

======================================================================
ERROR: test_basic (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_bytes (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_dir_entry (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_file_attributes (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_path (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_returns_iter (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_stat (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_symlink (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_unicode (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_walk_unicode_handling (test_scandir.TestScandirGeneric)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 279, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_basic (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_bytes (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_dir_entry (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_file_attributes (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_path (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_returns_iter (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_stat (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_symlink (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_unicode (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

======================================================================
ERROR: test_walk_unicode_handling (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 287, in setUp
    TestMixin.setUp(self)
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 97, in setUp
    setup_symlinks()
  File "/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/test_scandir.py", line 68, in setup_symlinks
    os.mkdir(join(TEST_PATH, 'linkdir', 'linksubdir'))
OSError: [Errno 2] No such file or directory: '/home/kth5/arch/archpower/python2-scandir/src/scandir-1.10.0/test/testdir/linkdir/linksubdir'

----------------------------------------------------------------------
Ran 24 tests in 0.008s

FAILED (errors=20)
==> ERROR: A failure occurred in check().
    Aborting...
==> Removing installed dependencies...
checking dependencies...
:: git optionally requires python2: various helper scripts
:: vim optionally requires python2: Python 2 language support

Packages (6) python2-2.7.15-7  python2-appdirs-1.4.3-2  python2-packaging-18.0-1  python2-pyparsing-2.3.1-1  python2-setuptools-1:40.6.3-1  python2-six-1.12.0-1

Total Removed Size:  74.45 MiB

:: Do you want to remove these packages? [Y/n] :: Processing package changes...
removing python2-setuptools...
removing python2-packaging...
removing python2-six...
removing python2-pyparsing...
removing python2-appdirs...
removing python2...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
